import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const membersList = [
  {
    name: "Vicky",
    prMerge: 0,
  },
  {
    name: "Sagar",
    prMerge: 1,
  },
  {
    name: "Vikash",
    prMerge: 1,
  },
  {
    name: "Harsh",
    prMerge: 0,
  },
  {
    name: "Saransh",
    prMerge: 0,
  },
];

function bubbleSort(membersList) {
  for (let i = 0; i < membersList.length; i++) {
    for (let j = 0; j < membersList.length - i - 1; j++) {
      if (membersList[j + 1].prMerge >= membersList[j].prMerge) {
        [membersList[j + 1], membersList[j]] = [
          membersList[j],
          membersList[j + 1],
        ];
      }
    }
  }
  return membersList;
}

bubbleSort(membersList);

export default function Home() {
  const [members, setMembers] = useState(membersList);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h3>Epvi Engineering Leader Board</h3>
        </div>
        <div>
          <table>
            <thead>
              <tr>
                <th>Rank</th>
                <th>S. No.</th>
                <th>PR Merge</th>
              </tr>
            </thead>
            <tbody>
              {members.map((member, i) => (
                <tr key={i}>
                  <td style={{textAlign: "center"}}>{i + 1}</td>
                  <td>{member.name}</td>
                  <td style={{textAlign: "center"}} >{member.prMerge}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
}
